# Generated by Django 5.1.1 on 2024-10-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
                'db_table': 'channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telegram_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'db_table': 'tickets',
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='MatchingStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='Bot.tickets')),
            ],
            options={
                'verbose_name': 'Соответствие',
                'verbose_name_plural': 'Соответствия',
                'db_table': 'matching_strings',
                'ordering': ['string'],
            },
        ),
    ]
