# Generated by Django 5.1.1 on 2024-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user_telegram_id',
            field=models.CharField(max_length=100),
        ),
    ]
